[project]
name = "aprendepython"
version = "2.2.1"
requires-python = ">=3.13"
dependencies = ["mkdocs-material>=9.6.8", "mkdocs-minify-plugin>=0.8.0"]

[dependency-groups]
dev = ["ipython>=9.0.2", "pytest>=8.3.5"]
